### ISSUE TITLE
UI Breaks with Long URLs in the Deployment Section

### ISSUE THREAD

**Issue by agberoz** [sirocco-ventures/raggenie#118]
In the Deployment section, when a long URL is displayed, the UI layout breaks or becomes misaligned, affecting the overall user experience.

**To Reproduce**
1. Spin up UI &  backend in GitHub workspaces
2. Go to the Deployment section

**Suggested solution**
Implement text wrapping, an ellipsis for truncation, or a scrollable text field to handle long URLs gracefully.

**Screenshots**
<img width="1114" alt="Screenshot 2024-10-15 at 3 03 47 PM" src="https://github.com/user-attachments/assets/fcff54f9-543f-457e-8c0b-51503293935d">

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by TechGeekRahul** [comment]
hi @agberoz  I want to work on this issue.can you assign it to me ?

**Comment by agberoz** [comment]
hi @TechGeekRahul,

Assigning this issue to you, happy coding

If any assistance is required meet our team here: https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by TechGeekRahul** [comment]
hey kindly accept my pr.
