### ISSUE TITLE
Style Formatting Getting Copied into User Query Input on Copy-Paste

### ISSUE THREAD

**Issue by agberoz** [sirocco-ventures/raggenie#120]
When a user copies content and pastes it into the query input, the style formatting (e.g., font, color, background) is being retained. 

**To Reproduce**
1. Go to Preview page
2. Copy styled content from any page and paste

**Expected behavior**
We want only the plain text to appear in the input box without any style formatting

**Screenshots**
<img width="756" alt="Screenshot 2024-10-15 at 6 42 19 PM" src="https://github.com/user-attachments/assets/70ec9679-83ec-4ade-aa48-371988b155a6">

**Comment by dexterousdhruv** [comment]
@agberoz  Could you please assign it to me ? Also, mention the file in which the bug resides. Would save me so time.

**Comment by ryumen-sukuna** [comment]
hi @dexterousdhruv,

Assigning this issue to you, happy coding

If any assistance is required meet our team here: https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by dexterousdhruv** [comment]
@agberoz  Kindly review the PR.

**Comment by agberoz** [comment]
@sethumadhavan-k ,  Please check the PR

**Comment by dexterousdhruv** [comment]
@sethumadhavan-k I've created a fresh PR. Please review it.
