### ISSUE TITLE
Missing 'eslint-plugin-react' Package When Running npm run lint

### ISSUE THREAD

**Issue by sethumadhavan-k** [sirocco-ventures/raggenie#127]
When attempting to run the linting command (npm run lint), an error is encountered due to the absence of the eslint-plugin-react package.

<img width="1159" alt="Screenshot 2024-10-17 at 11 46 31 AM" src="https://github.com/user-attachments/assets/437d0eb1-2d92-4e67-85aa-17caf37fcfe7">

**Steps to Reproduce:**

- Clone the repository.
- Run `npm install`.
- Execute `npm run lint`.

**Solution:** To resolve this issue, please install the missing package by running the following command:
`npm install eslint-plugin-react`

**Comment by nishammahsin** [comment]
Please assign this to me

**Comment by sethumadhavan-k** [comment]
@nishammahsin assign this issue to you, happy coding
