### ISSUE TITLE
Add Dockerfile for Backend App to Build and Run in Python

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#14]
Add a Dockerfile to containerize the backend application, allowing it to be built and run in a Python environment.
	•	Use an Alpine-based image for a lightweight container.
	•	No need to include or pass any config file, as it is planned to be removed before first release.
	•	The application should expose port 8080.

**Comment by leinadsened** [comment]
Hello, I would like to have a try with this issue, could you please assign it to me?

**Comment by ashmilhussain** [comment]
Hey @leinadsened  ,

Assigning this issue to you, happy coding

If any assistance required meet our team here : https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by agberoz** [comment]
HI @leinadsened  any updated on this ?

**Comment by leinadsened** [comment]
Hi @agberoz @ashmilhussain 
Created a PR #68

**Comment by agberoz** [comment]
@leinadsened, Please go through the review comment

**Comment by leinadsened** [comment]
Thank you for the detailed review @agberoz

I had a feeling my understanding of the task was a bit simple 😅 I'm sure I will have some questions, will start working on it later today.

**Comment by agberoz** [comment]
@leinadsened,  I've mentioned two changes. 

Once they're done, the PR will be ready to merge.

**Comment by leinadsened** [comment]
@agberoz, I'm finished 😄 
Thank you for the guidance, it was a great experience!
