### ISSUE TITLE
Add Dockerfile for ReactJS Application

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#15]
Create a Dockerfile to containerize the ReactJS application with the following requirements:
•	Use a lightweight Alpine-based image.
•	Ensure the app runs on port 5000.
•	Pass the backend URL and port value through the configuration file or environment variables.

**Comment by RINO-GAELICO** [comment]
Hi @ashmilhussain I'd like to tackle this issue. 
Would you assign it to me?

**Comment by ashmilhussain** [comment]
Hi @RINO-GAELICO assigned the task you can follow contrubution guidelines mentioned on Readme.md and make a PR

**Comment by RINO-GAELICO** [comment]
Hi @ashmilhussain, to pass the backend URL as env variables should I create an .env file and then do something like this:
```
COPY .env .env
ARG BACKEND_URL
ENV BACKEND_URL=${BACKEND_URL}
```

Should I do the same for the port value?

Also, I see that there is already a Dockerfile in the repo, should I modify that one?

**Comment by ashmilhussain** [comment]
Hi @RINO-GAELICO  yes, please work on existing docker and add a .env file add a example env file also to help users

the idea is anyone should be able to run the docker seamlessly without much support

Please join slack if you need any support : https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by RINO-GAELICO** [comment]
Thanks for the clarification. I created a PR following your guidelines

**Comment by ashmilhussain** [comment]
Sure @RINO-GAELICO , will merge once tested and reviewed by @sethumadhavan-k
