### ISSUE TITLE
Add MySQL Plugin

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#16]
We need to enhance RAGGENIE by adding support for MySQL as a data source plugin. This will enable users to connect and retrieve data from MySQL databases within the RAGGENIE platform.

Implement a MySQL plugin for data retrieval and integration.
•	Ensure compatibility with existing RAGGENIE architecture for low-code RAG building.
•	Provide configuration options for MySQL connection details (host, port, username, password, database).

For referance check the existing PostgreSQL plugin

**Comment by syfuuu** [comment]
@ashmilhussain I can work on this.

**Comment by ashmilhussain** [comment]
@syfuuu sure, assigned it you , happy coding

**Comment by agberoz** [comment]
@syfuuu Any update on this ?

**Comment by sethumadhavan-k** [comment]
@syfuuu reassigning this issue due to inactivity
