### ISSUE TITLE
Add alert notification for bot restart after Bot configuration changes 

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#20]
After changing any bot configuration, users currently do not receive clear instructions regarding the need to restart the bot.

Implement an alert notification after saving configuration changes.
The notification should state: "Please restart the bot to get changes to take effect."

**Comment by Gak1o** [comment]
I can do this too

**Comment by ashmilhussain** [comment]
Hey @Gak1o  ,

Assigning this issue to you, happy coding

If any assistance required meet our team here : https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by ashmilhussain** [comment]
@Gak1o will reassign since no response so far, please update if you are already working

**Comment by abhishekas7** [comment]
I wish to do this issue. @sethumadhavan-k  can you assign me to do this issue .
