### ISSUE TITLE
Create documentation website using docusaurus

### ISSUE THREAD

**Issue by ArjunPA2001** [sirocco-ventures/raggenie#25]
A documentation website needs to be established using docusaurus to provide comprehensive instructions on how to run and configure the raggenie application. This documentation enhancement aims to improve accessibility and usability for users.

**Comment by Gak1o** [comment]
Kindly assign this to me

**Comment by ashmilhussain** [comment]
@Gak1o  noticed you are already requested on another one, I will assign this to you once we the PR is in progress

im adding more issues so keep an eye

**Comment by IntegerAlex** [comment]
Do one need to ask for assignment or should discuss and then get assigned. I am confused

**Comment by ashmilhussain** [comment]
@IntegerAlex  if you are intrested let me know i will assign then you can do the PR

**Comment by thompsgj** [comment]
If this issue is still available, I'd like to work on it.
