### ISSUE TITLE
Reduce minimum length for title and description on Plugin and Bot Configuration pages

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#28]
The minimum length requirements for the fields on the Plugin and Bot configuration pages are too high, leading to unnecessary restrictions

Reduce the minimum length for the following fields:
•	Plugin Name: Set to 10 characters (currently higher)
•	Plugin Description: Set to 20 characters
•	Bot Long Description: Set to 50 characters

**Comment by gabrilito1** [comment]
done
