### ISSUE TITLE
Add placeholder and hint for URL input box on Website Plugin Configuration Page

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#29]
The URL input box for the Website Plugin does not currently have a placeholder, which may confuse users regarding the required format (HTTP or HTTPS).

Proposed Changes:

**Add a placeholder to the URL input box:**
	•	Placeholder text: https://www.raggenie.com
**Include a hint below the input box stating:**
	•	“Include http or https in the URL.”

**Comment by uchiha-vivek** [comment]
Sir can you please assign this issue to me . I have tried to fixed it 

**BEFORE**

![before](https://github.com/user-attachments/assets/0778e3fb-8d01-4891-a137-da53e8c6d4f7)

**AFTER**
![after](https://github.com/user-attachments/assets/783bf9e2-6e9e-4695-8ebf-149557ac1055)

Changes made in File : 
ui>src>components>SearchInput.jsx
ui>src>components>SearchInput.module.css

**Add a placeholder to the URL input box:**
**Include a hint below the input box stating:**

**Comment by ashmilhussain** [comment]
Hi @uchiha-vivek  sorry to miss adding screnshots

Firstly appriciating your quick effort and result ,  unfortunately this is not the screen where it was required

This is the Samle path : /plugins/4/website/2/details

**Screenshot marked the field**

<img width="1512" alt="Screenshot 2024-09-28 at 3 14 42 PM" src="https://github.com/user-attachments/assets/476d773c-7c75-4022-bd32-5412cde42fba">

> You need to run the backend also to see the pluggin list, currently i can see plugins are not loaded on your screen

**Comment by uchiha-vivek** [comment]
Yes @ashmilhussain noted, Will do it.

**Comment by uchiha-vivek** [comment]
**Changes Made **

![raggenie](https://github.com/user-attachments/assets/6719e22b-7290-4292-92cd-e5f4742db20f)

I tried to run the backend and then made the changes successfully .

**Comment by uchiha-vivek** [comment]
@ashmilhussain  we have to create seperate branch_name by feature or issue  name right ?

**Comment by ashmilhussain** [comment]
Will update once reviewed, regarding branch let it go to main for now

**Comment by uchiha-vivek** [comment]
Ok @ashmilhussain   Thanks
