### ISSUE TITLE
Remove Finish Button on Capabilities Screen

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#31]
The Finish button on the Capabilities screen is unnecessary because data is already being saved to the backend using the “Save and Continue” buttons on previous tabs, and each capability has separate save buttons.

Proposed Changes:

•	Remove the Finish button from the Capabilities screen along with any related code.

**Comment by PartishtaP** [comment]
Hey @ashmilhussain assign me the issue.
I would like to contribute.

**Comment by ashmilhussain** [comment]
Hey @PartishtaP ,

Assigning this issue to you, happy coding

If any assistance required meet our team here : https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by agberoz** [comment]
@PartishtaP Any update on this ?

**Comment by sethumadhavan-k** [comment]
Unassigning @PartishtaP  from this issue due to inactivity.

**Comment by abhishekas7** [comment]
I would like to do this issue. @sethumadhavan-k Can you please assign me?

**Comment by sethumadhavan-k** [comment]
Hey @abhishekas7 

Assigning this issue to you,
