### ISSUE TITLE
Add confirmation dialog for plugin deletion

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#35]
Currently, when attempting to delete a plugin, there is no confirmation dialog, which may lead to accidental deletions. A confirmation dialog should be added to improve user experience and prevent unintended actions.

	•	Prompt text: “Do you want to delete?”
	•	Buttons: “Delete” and “Cancel”
	
	
![Frame 1000006337](https://github.com/user-attachments/assets/34ebaf84-7924-43b0-9766-f9832bb21830)

**Comment by itsharshitrwt** [comment]
Can i start working on this  issue plz ?

**Comment by kart2004** [comment]
Hello, I would like to work on this issue. Could someone please assign it to me?

**Comment by uchiha-vivek** [comment]
@ashmilhussain  Sir i have almost solved this issue , Currently working on designing the confirmation dialog box .

![Screenshot (102)](https://github.com/user-attachments/assets/5f1b7396-55d7-4abd-875f-5b1e242c4fc5)

@ashmilhussain  Is the dialog box already present or we need to make it manually ?
