### ISSUE TITLE
API Key Input Field Should Be Password Type in Inference Endpoint Form

### ISSUE THREAD

**Issue by agberoz** [sirocco-ventures/raggenie#46]
The API key input field in the inference endpoint form of the Bot Configuration section is currently not set to password type, which can expose sensitive information.

<img width="1440" alt="Screenshot 2024-09-30 at 4 12 40 PM" src="https://github.com/user-attachments/assets/2f0cd739-99b3-40cd-85ba-bbf37f77b957">

**Steps to Reproduce:**
1. Spin up Raggenie UI & backend
1. Open the Bot Configuration.
2. Complete the first step.
3. Navigate to the inference endpoint form.

**Specific File Affected:**
- `raggenie/ui/src/pages/ChatConfiguration/ChatConfiguration.jsx`

**Proposed Solution:**
Change the input type of the API key field to `password` to ensure data security.

**Comment by uchiha-vivek** [comment]
@agberoz  Sir i have fixed this issue . 
![password](https://github.com/user-attachments/assets/94b6e00a-c20c-48bd-ac37-55f4028f112e)
