### ISSUE TITLE
Save Button Appears Without Re-testing After Credential Changes in Plugin Form

### ISSUE THREAD

**Issue by agberoz** [sirocco-ventures/raggenie#47]
In the plugin form, after a user successfully tests the credentials, the "Save" button becomes available. However, if the user makes any changes afterward, the "Test Connection" button does not reappear, allowing the user to save without re-testing.

**Steps to Reproduce:**
1. Navigate to Plugins.
2. Click on "Add Plugin."
3. Fill in all required details and proper credentials.

    <img width="1425" alt="Screenshot 2024-09-30 at 4 40 13 PM" src="https://github.com/user-attachments/assets/63af7a81-3720-42d7-83ca-10c516682696">
4. Click on "Test Connection."
5. Make any changes to the form, Test connection won't reappear, and save button is enabled

    <img width="1440" alt="Screenshot 2024-09-30 at 4 40 57 PM" src="https://github.com/user-attachments/assets/ad518ddf-bcf4-4e4d-ba8e-f7992ce7e818">

    

**Specific File Affected:**
- `raggenie/ui/src/pages/Configuration/ProviderForm/ProviderForm.jsx`

**Proposed Solution:**
- Disable the "Save" button when any changes are made and re-enable the "Test Connection" button

**Comment by uchiha-vivek** [comment]
@agberoz  Please assign me this issue

**Comment by abhishekas7** [comment]
Hello, I would like to work on this issue. Could someone please assign it to me?
