### ISSUE TITLE
Users Can Add Samples to Non-Database Plugins, Disrupting System Functionality

### ISSUE THREAD

**Issue by agberoz** [sirocco-ventures/raggenie#53]
The section designated for creating sample questions and answers is intended solely for database plugins. However, users are able to add samples for non-database plugins, leading to system disruptions.

**Steps to Reproduce:**
1. Add a website plugin.
2. Go to the Samples section.
3. Attempt to add samples
    
    <img width="1440" alt="Screenshot 2024-09-30 at 6 09 39 PM" src="https://github.com/user-attachments/assets/408afefa-88d2-41c3-82c6-f3dfd432ef1f">
    

**Specific File Affected:**
- `raggenie/app/api/v1/connector.py`

**Proposed Solution:**
- Modify the handler for `/api/v1/connector/list` to support filters
- Filter the plugins with `provider_category_id == 2` (database plugins).
- If no filters, then return the complete list

**Comment by RINO-GAELICO** [comment]
Hi @agberoz I would like to tackle this issue. Can i have it assigned it?

**Comment by agberoz** [comment]
Hello @RINO-GAELICO,

* The optional query parameter should be passed accordingly, which will require a minor frontend adjustment. The front end should now pass the optional filters when necessary. 

* Please implement a filtering mechanism within `list_connectors`. 

I am assigning the issue to you. Happy coding!

If you need any support, feel free to reach out to the team via Slack: [Join here](https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw).

**Comment by RINO-GAELICO** [comment]
I created a PR. Let me know if you have any comments. Check out PR #107

**Comment by agberoz** [comment]
@sethumadhavan-k  please review

**Comment by sethumadhavan-k** [comment]
@RINO-GAELICO Please pass the provider_category_id parameter with a value of '2' in the getConnectors() function located in src/pages/Samples/SampleForm.

**Comment by RINO-GAELICO** [comment]
@sethumadhavan-k I did. 
I passed as int not as character '2'. Let me know if I need to change that.

**Comment by RINO-GAELICO** [comment]
@agberoz What is the provide_category_id among these properties?
```
        connector_id=connector.id,
        connector_type=connector.connector_type,
        connector_name=connector.connector_name,
        connector_description=connector.connector_description,
        connector_config=connector.connector_config,
        schema_config=connector.schema_config,
        connector_docs=connector.connector_docs,
        connector_key=connector.provider.key,
        enable=connector.enable,
        icon=connector.provider.icon
```
