### ISSUE TITLE
Implement Basic Authentication Middleware

### ISSUE THREAD

**Issue by sajosam** [sirocco-ventures/raggenie#81]
Add a basic authentication middleware to manage user authentication in the application, while excluding chat routes from this authentication process.

**Proposed Solution:**
1. Load the username and password from environment variables.
2. Implement middleware to handle authentication for necessary routes.
3. Ensure that chat routes are exempted from authentication.

**Comment by nishammahsin** [comment]
Can I work on this issue?

**Comment by abhishekas7** [comment]
Video Link : 
 
 https://www.loom.com/share/ef172d3b35df4a758b09bc0879e2e1e1?sid=9b4de1d3-9979-4e99-a93e-6d7687a192e5
