### ISSUE TITLE
Create a Docker Compose File for Running Raggenie

### ISSUE THREAD

**Issue by agberoz** [sirocco-ventures/raggenie#96]
Users are facing difficulties in setting up Raggenie locally due to the multiple components involved in running both the frontend and backend. Currently, the setup process requires manually managing these components and dependencies, which can be time-consuming and prone to errors.

**Describe the solution you'd like**
To improve the developer experience, a Docker Compose file is needed. This Docker Compose setup should:
  1. Facilitate the easy setup and running of Raggenie locally.
  2. Include both the frontend and backend services.

**Comment by leinadsened** [comment]
Hi @agberoz 
I'd like to work on this one, could you please assign me to it?

**Comment by agberoz** [comment]
Hey @leinadsened ,

Assigning this issue to you, happy coding

If any assistance is required meet our team here: https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by leinadsened** [comment]
Hey @agberoz submitted my work in #102

Wasn't sure on the version so went with 3.8.
Back-end is started with "python main.py --config ./config.yaml llm" so the application is available on localhost:8080 after running a single command "docker-compose up --build", but I don't know if that's a good solution.
